device: /dev/ttyUSB1
frame_id: gps

uart1:
  baudrate: 115200

config_on_startup: false
tmode3: 0

publish:
  all: false
  nav:
    all: true
    navpvt: true
    relposned: true
    poslih: true
    posecef: true
